language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: 4809c7a2-9074-4b5a-9e01-0e15f0d7525c
  app: react-trello-testing
  on:
    repo: rrogerthat/react-trello-testing
