language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: sAjrKdlLkCqw9M/5pN2uqmj4Uyc5SlDBKvL7YG6hIDbp4aDqru922sva3oqe/tdPj10NDt64CpcPmr1ks8avI1MpLxPasJ6GdNXGlCakzZvazNmUmsCpeyuHP31a5AXycTorIdWK+pvGJJEdch7/CNbc5eV+UdiVcSQL08IkH2KTkFWmEAXx4GlaKorUPiho35q/3KVAV9zwrnIL1maWZjqx1oxcyg0ubk2EoPyZ8wiM4EP8L9qmOGvm830PMpPvgTXK8rMAhHNDIR5PzcyKSWyE+uD8fGWRSlbBSqCj0rKkhWGypmBTdrfrU7e7ndAhASIi3NtbwjBhvtIdsphcmcovyF1EOJ4AdqRE0apGd9jTQE+JiJhIwAoyM9tnLmBVDjMEadkGL+pDVH0qa/WyOhlegHzzLgSBBA/thGb5YlQ1WxOS80djxGM4gndXMuG81noEreEgrgErP0qTXG2xfzS1KglJbAWMA/sBq10pt1rPViYBtR2elASvEJqg1mRgm9nVbzMikH5CecRmpMursxbpGGN8WwflzNFgf4WtbzE0VBxe7y8SCpUrtWMe/miLcIEMnBBM/vj/aJG+QfrCdSiFgHBTXe57inIHecBFVzNDWOrk34nSC90SYaFFx64j9JUwS+pNVBXoX9CqhlMaYeuo0p1lKRG8xTqoCda4Vos=
  app: stormy-beyond-61979
  on:
    repo: rrogerthat/react-trello-testing
